# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd124bfa0a04bf949232107a8711f76c01b8fc846abb863e9318c64dbb1bf8ea8e9eb17a14f1a3e53cda69c6c08c7c196b2ba3a4bb6beab513d04ddb54e5468d

test:
  secret_key_base: 6bf230652b5af1e34d6b042e960acb876840bc35de4e9cfe3cf24b2cace12733db8715facf8bef8449c021ffb790a233214bde1cacfb4d46da3ecb50207b4458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
